@startuml
'https://plantuml.com/component-diagram
package "HTTP API"{
    [ddd-start]
    [ddd-web]
}

package "RPC API"{
    [ddd-client]
    [ddd-client-impl]
}


[ddd-start] --> [ddd-web]

[ddd-web] --> [ddd-service]

[ddd-client] --> [ddd-bean]

[ddd-client-impl] --> [ddd-client]
[ddd-client-impl] --> [ddd-service]

[ddd-service] --> [ddd-core]
[ddd-service] --> [ddd-bean]
[ddd-service] --> [ddd-integration]

[ddd-core] --> [ddd-bean]
[ddd-core] --> [ddd-dao]
[ddd-core] --> [ddd-common]
@enduml